### ISSUE TITLE
none rather than transparent

### ISSUE THREAD

**Issue by SaitoAtsushi** [lukaslueg/railroad#14]
https://github.com/lukaslueg/railroad/blob/61a1af6a8124ede9b48f7c42ec9c797111c52f68/src/lib.rs#L98

[css's "transparent"](https://www.w3.org/TR/css-color-4/#valdef-color-transparent) means "transparent black".
Some software that cannot handle transparency will fill it with black.
I suggest that to specify none.

**Comment by lukaslueg** [comment]
Thanks for the hint. Could you clarify "some software"?

**Comment by SaitoAtsushi** [comment]
Online converter [convertio](https://convertio.co/ja/), [aconvert](https://www.aconvert.com/image/) and [CDKM](https://cdkm.com/) cannot handle transparency.

[Inkscape](https://inkscape.org/) can handle transparency but does not separate stroke and fill.
SVG is broken when to import by Inkscape.
